# Generated by Django 5.1.1 on 2024-12-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0002_cartoon_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='description',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='cartoon',
            name='era',
            field=models.CharField(max_length=100, verbose_name='時代'),
        ),
        migrations.AlterField(
            model_name='cartoon',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='cartoon',
            name='year',
            field=models.CharField(max_length=100, verbose_name='年代'),
        ),
    ]
