# Generated by Django 5.1.1 on 2024-12-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0003_alter_cartoon_description_alter_cartoon_era_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='year',
            field=models.CharField(max_length=100, verbose_name='年間'),
        ),
    ]
